improve logging convention

diff --git a/project-skel/bin/ci b/project-skel/bin/ci
--- a/project-skel/bin/ci
+++ b/project-skel/bin/ci
@@ -1,15 +1,13 @@
 #!/usr/bin/env bash
+# This project is AnyCI enabled. https://github.com/briceburg/anyci for more!
 set -eo pipefail
 readonly PROJECT_ROOT="$( cd "$(dirname "$0")/.." ; pwd -P)"
-log(){ echo -e "bin/ci: $*" >&2; }
-die(){ log "[ERR] $*"; exit 1; }
-
 ANYCI_HOME="${ANYCI_HOME:-$HOME/.anyci}"
 ANYCI_BOOTSTRAP_URL="${ANYCI_BOOTSTRAP_URL:-https://github.com/briceburg/anyci-bootstrap.git}"
 
 [ -d "$ANYCI_HOME/anyci-bootstrap" ] || {
-  log "missing anyci-bootstrap. intalling now..."
-  git clone "$ANYCI_BOOTSTRAP_URL" "$ANYCI_HOME/anyci-bootstrap" 2>&1 | sed "s/^/    /g"
+  echo "# $0: missing anyci-bootstrap. intalling now..." >&2;
+  git clone "$ANYCI_BOOTSTRAP_URL" "$ANYCI_HOME/anyci-bootstrap" 2>&1 | sed "s/^/#    /g"
 }
 
 export PROJECT_ROOT
